# Generated by Django 4.2.20 on 2025-07-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_post_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='none', max_length=800),
            preserve_default=False,
        ),
    ]
